application: ws-g-1234
version: 1
runtime: go
api_version: go1

handlers:
- url: /.*
  script: _go_app

# run in local
# > goapp serve

# deploy
# > goapp deploy

# url
# http://ws-g-1234.appspot.com/